import Testing
import SwiftUI
@testable import MacFaceKit

/// `Brand` must never be able to take an app down (400faces/MacFaceKit#1).
///
/// It already had a fallback - `Image(systemName: "link")` when the asset is missing - and that
/// fallback was UNREACHABLE. `Bundle.module` is generated by SwiftPM and calls `fatalError` when it
/// cannot find its bundle, so the guard below it never ran: the process trapped first.
///
/// That is not theoretical. PushText 0.2.0 shipped, and crashed on first launch for its only user
/// with `EXC_BREAKPOINT` in `variable initialization expression of static NSBundle.module`, because
/// the generated accessor falls back to an ABSOLUTE BUILD PATH baked in at compile time - which
/// exists on the machine that built the app and nowhere else.
///
/// WHAT THESE TESTS CANNOT SEE, and it is the important half: they run ON the build machine, where
/// that absolute path EXISTS. The broken version passes them too. They cover the fallback path and
/// the totality of the lookup; they cannot cover the defect that shipped. Only running a packaged
/// app with the build directory made unavailable can do that, which is why the real guard lives in
/// the consuming app's build script rather than here.
@Suite("Brand")
struct BrandTests {

    /// The whole point: resolving a mark must return an Image rather than trap, whatever the
    /// filesystem looks like.
    @Test("A known mark resolves without trapping")
    func knownMarkResolves() {
        _ = Brand.github
    }

    /// A name that is definitely not bundled exercises the fallback path that used to be dead code.
    @Test("An unknown mark falls back instead of crashing")
    func unknownMarkFallsBack() {
        _ = Brand.mark("definitely-not-a-bundled-brand-mark")
    }

    /// The bundle lookup itself must be total. `Bundle.module` is not - that is the defect - so this
    /// asserts the replacement never traps even when it finds nothing.
    @Test("Resolving the resource bundle never traps")
    func bundleLookupIsTotal() {
        _ = Brand.resourceBundle
    }
}
